name: Generate Corrective RAG MLFlow Documentation

on:
  workflow_dispatch:
    inputs:
      query:
        description: "The question to answer"
        required: true
      experiment_id:
        description: "MLFlow experiment ID"
        required: true
      mlflow-tracking-server:
        description: "The hosted URL of the MLflow server"
        required: false
        default: "http://127.0.0.1:5000"
  
jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with: 
           query: ${{ github.event.inputs.query }}
           experiment-id: ${{ github.event.inputs.experiment_id }}
           start-mlflow-server: ${{ github.event.inputs.mlflow-tracking-server == 'http://127.0.0.1:5000' }}
           mlflow-tracking-uri: ${{ github.event.inputs.mlflow-tracking-server }}
           anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
        
